# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'heatMap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for heatMap
  pod 'GoogleMaps', '= 2.3.0'
  pod 'Google-Maps-iOS-Utils'
end
